esphome:
  name: sml
  platform: ESP8266
  # board: d1_mini_pro
  board: d1_mini

external_components:
  - source:
      type: local
      path: components
    components: [ sml ]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    # static_ip: 192.168.2.70
    static_ip: 192.168.2.64
    gateway: 192.168.2.1
    subnet: 255.255.255.0

captive_portal:

# Enable logging
logger:
  hardware_uart: UART1
  level: DEBUG

# Enable Home Assistant API
api:

ota:

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

sml:
  id: mysml
  uart_id: uart_bus

sensor:
  - platform: wifi_signal
    name: "SML WiFi Signal Sensor"
    update_interval: 10s

  - platform: sml
    name: "Total energy"
    sml_id: mysml
    # server_id: "080534d12d4c4bb9"
    obis: "1-0:1.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 1
    filters:
      - multiply: 0.0001

  - platform: sml
    name: "Total energy 1"
    sml_id: mysml
    # server_id: "080534d12d4c4bb9"
    obis: "1-0:1.8.1"
    unit_of_measurement: kWh
    accuracy_decimals: 1
    filters:
      - multiply: 0.0001

  - platform: sml
    name: "Total energy 2"
    sml_id: mysml
    # server_id: "080534d12d4c4bb9"
    obis: "1-0:1.8.2"
    unit_of_measurement: kWh
    accuracy_decimals: 1
    filters:
      - multiply: 0.0001

  - platform: sml
    name: "Active power"
    sml_id: mysml
    # server_id: "080534d12d4c4bb9"
    obis: "1-0:15.7.0"
    unit_of_measurement: Wh
    filters:
      - multiply: 0.1
    accuracy_decimals: 1

text_sensor:
  - platform: sml
    name: "Manufacturer"
    sml_id: mysml
    # server_id: "080534d12d4c4bb9"
    obis: "129-129:199.130.3"
    format: text

  - platform: sml
    name: "Total energy Hex"
    sml_id: mysml
    # server_id: "080534d12d4c4bb9"
    obis: "1-0:1.8.0"
    format: hex

  - platform: sml
    name: "Total energy String"
    sml_id: mysml
    # server_id: "080534d12d4c4bb9"
    obis: "1-0:1.8.0"
    # format: uint
